### ISSUE TITLE
Error when renewing token

### ISSUE THREAD

**Issue by NeoWeb-JP** [mattcollins171/oauth2-osm#1]
PHP Warning:  Illegal string offset 'message' in /home/thamesridgescout/dev.thamesridgescouts.org.uk/wp-content/plugins/neoweb-connector/includes/libs/3rd-party/mattcollins171/oauth2-osm/src/Provider/Osm.php on line 124

**Comment by NeoWeb-JP** [comment]
Full stack trace:

PHP Warning:  Illegal string offset 'message' in /home/thamesridgescout/dev.thamesridgescouts.org.uk/wp-content/plugins/neoweb-connector/includes/libs/3rd-party/mattcollins171/oauth2-osm/src/Provider/Osm.php on line 124
[18-Feb-2021 17:28:17 UTC] PHP Warning:  Illegal string offset 'code' in /home/thamesridgescout/dev.thamesridgescouts.org.uk/wp-content/plugins/neoweb-connector/includes/libs/3rd-party/mattcollins171/oauth2-osm/src/Provider/Osm.php on line 124
[18-Feb-2021 17:28:17 UTC] PHP Fatal error:  Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: 401 - The refresh token is invalid.: i : i in /home/thamesridgescout/dev.thamesridgescouts.org.uk/wp-content/plugins/neoweb-connector/includes/libs/3rd-party/mattcollins171/oauth2-osm/src/Provider/Osm.php:123
Stack trace:
#0 /home/thamesridgescout/dev.thamesridgescouts.org.uk/wp-content/plugins/neoweb-connector/includes/libs/3rd-party/league/oauth2-client/src/Provider/AbstractProvider.php(628): mattcollins171\OAuth2\Client\Provider\Osm->checkResponse(Object(GuzzleHttp\Psr7\Response), Array)
#1 /home/thamesridgescout/dev.thamesridgescouts.org.uk/wp-content/plugins/neoweb-connector/includes/libs/3rd-party/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request))
#2 /home/thamesridgescout/dev.thamesridgescouts.org.uk/wp-content/plugins/neoweb-connector/utils/class-neoweb-connector-auth-caller.php(238): League\OAuth2\Client\Provider\Abstr in /home/thamesridgescout/dev.thamesridgescouts.org.uk/wp-content/plugins/neoweb-connector/includes/libs/3rd-party/mattcollins171/oauth2-osm/src/Provider/Osm.php on line 123
